### ISSUE TITLE
证书生成相关文件再哪里？

### ISSUE THREAD

**Issue by jamchina** [cby-chen/Kubernetes#11]
二进制部署k8s 1.23.6 生成证书相关文件在哪里？而且感觉文档跟这做都整不出来，跟着文档来弄的，基础没那么好的。

**Comment by cby-chen** [comment]
![image](https://user-images.githubusercontent.com/46200206/170862450-fa969f0e-2a39-43fd-b5e4-05c0972b8621.png)

选一下版本

**Comment by cby-chen** [comment]
确实不容易，得研究研究，我有基础，自己研究了一个多月才搞懂
