### ISSUE TITLE
kubernetes1.24.1安装metric时出现的问题

### ISSUE THREAD

**Issue by 2822132073** [cby-chen/Kubernetes#13]
我的k8s版本是1.24.1
大佬,我用了你的metric的yaml,但我是使用kubeadm安装的,在安装后,执行 top no显示
`[root@master-1 ~]# kubectl top no
NAME       CPU(cores)   CPU%        MEMORY(bytes)   MEMORY%     
master-2   436m         10%         2387Mi          41%         
master-3   <unknown>    <unknown>   <unknown>       <unknown>   
node-1     <unknown>    <unknown>   <unknown>       <unknown>   
node-2     <unknown>    <unknown>   <unknown>       <unknown>   
master-1   <unknown>    <unknown>   <unknown>       <unknown>   
[root@master-1 ~]# 
`
在日志里面发现
`
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.211:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="master-1"                │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.213:10250/stats/summary?only_cpu_and_memory=true\": dial tcp 172.16.0.213:10250: i/o timeout" node="master-3" │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.214:10250/stats/summary?only_cpu_and_memory=true\": dial tcp 172.16.0.214:10250: i/o timeout" node="node-1"   │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.215:10250/stats/summary?only_cpu_and_memory=true\": dial tcp 172.16.0.215:10250: i/o timeout" node="node-2"   │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.213:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="master-3"                │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.215:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="node-2"                  │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.211:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="master-1"                │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.214:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="node-1"                  │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.214:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="node-1"                  │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.215:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="node-2"                  │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.213:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="master-3"                │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.211:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="master-1"                │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.213:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="master-3"                │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.215:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="node-2"                  │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.214:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="node-1"                  │
│ craper.go:139] "Failed to scrape node" err="Get \"https://172.16.0.211:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="master-1"    
`
麻烦问一下,这个是什么问题嘛

**Comment by cby-chen** [comment]
https://zhuanlan.zhihu.com/p/523927494  我刚写了新的文章，你可以看看，我安装是正常的

**Comment by 2822132073** [comment]
发现是calico出现问题了

**Comment by 2822132073** [comment]
关闭了
