### ISSUE TITLE
8.2.4   kubectl get node      not resources found

### ISSUE THREAD

**Issue by boboyada** [cby-chen/Kubernetes#5]
这是我搜索到的安装步骤最全面的文档，所以打算以此为起点，学习安装环境。

**#kubectl get node**
not resources fournd!  没有一个node出现。正常情况下，至少出现k8s-node01/03 not ready的状态。

但是仔细比对过。kubectl get cs 是正常的。
**[root@k8s-master01 ~]# kubectl get cs**
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                         ERROR
scheduler            Healthy     ok
controller-manager   Healthy     ok
etcd-1               Healthy     {"health":"true","reason":""}
etcd-0               Healthy     {"health":"true","reason":""}
**这篇文章是否直到”8.2.4“的安装前的步骤，有漏掉的？下面的两个包，下载后，在8.2.4步骤前，没有解压的文档**
        6.cni插件下载
       wget https://github.com/containernetworking/plugins/releases/download/v1.0.1/cni-plugins-linux-amd64-v1.0.1.tgz
        7.crictl客户端二进制下载
       wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.23.0/crictl-v1.23.0-linux-amd64.tar.gz
**安装步骤有一个现象：**
# yum install containerd -y
已加载插件：fastestmirror
.............................................
软件包 containerd-1.2.14-1.el7.x86_64 被已安装的 containerd.io-1.6.4-3.1.el7.x86_64 取代
无须任何处理
------------------------------是否前面安装文档中没有指定docker-ce的版本，导致最新的docker-ce依赖被安装？

下面的截取的一个bug：
#journalctl -xue  kubelet ....
5月 10 23:56:22 k8s-master01 kubelet[8608]: E0510 23:56:22.153703    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:22 k8s-master01 kubelet[8608]: E0510 23:56:22.254197    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:22 k8s-master01 kubelet[8608]: E0510 23:56:22.354494    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:22 k8s-master01 kubelet[8608]: E0510 23:56:22.454806    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:22 k8s-master01 kubelet[8608]: E0510 23:56:22.555280    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:22 k8s-master01 kubelet[8608]: E0510 23:56:22.655561    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:22 k8s-master01 kubelet[8608]: E0510 23:56:22.755981    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:22 k8s-master01 kubelet[8608]: E0510 23:56:22.856384    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:22 k8s-master01 kubelet[8608]: E0510 23:56:22.956755    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.058314    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.160477    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.260945    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.361353    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.461753    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.562193    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.664359    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.764898    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.865259    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.909965    8608 kubelet.go:2386] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady
5月 10 23:56:23 k8s-master01 kubelet[8608]: E0510 23:56:23.966519    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:24 k8s-master01 kubelet[8608]: E0510 23:56:24.066883    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:24 k8s-master01 kubelet[8608]: E0510 23:56:24.167430    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:24 k8s-master01 kubelet[8608]: E0510 23:56:24.267816    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:24 k8s-master01 kubelet[8608]: E0510 23:56:24.368271    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:24 k8s-master01 kubelet[8608]: E0510 23:56:24.468608    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:24 k8s-master01 kubelet[8608]: E0510 23:56:24.569051    8608 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 10 23:56:24 k8s-master01 kubelet[8608]: E0510 2

---==-
[root@k8s-master01 .kube]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.1.81 k8s-master01
192.168.1.82 k8s-master02
192.168.1.83 k8s-master03
192.168.1.84 k8s-node01
192.168.1.85 k8s-node02
192.168.1.86 k8s-node03
192.168.1.87 k8s-node04
192.168.1.88 k8s-node05
192.168.1.80 lb01
192.168.1.90 lb02

lb01,lb02也可以漂移

**Comment by boboyada** [comment]
已经解决。 --node-labels=node.kubernetes.io/node=''  删除即可

**Comment by RobKing9** [comment]
删除还是没有用
master节点 查看只有一个 
[root@k8s-master1 bootstrap]#  kubectl get nodes
NAME          STATUS   ROLES    AGE    VERSION
k8s-master1   Ready    <none>   8m4s   v1.25.4
node 节点 报错
[root@k8s-node1 ~]#  kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
