### ISSUE TITLE
Binary_installation_of_Kubernetes.sh 脚本版本，和手工版本的错误是一样的。

### ISSUE THREAD

**Issue by boboyada** [cby-chen/Kubernetes#6]
我是k8s的初学者。一直想完整的做一次二进制安装，以便多一点了解。但是失败了。
cby-chen老师的文档很全，花费了很多的时间，水平很高！
但是，我耗费了很多的时间去理解，去比对自己哪个地方没有正确的输入。
今天，又花费了一天，下载了脚本版；Binary_installation_of_kubernetes.sh.   
脚本中， 由于要reboot。所以，我手工把set_local,  init_all手工完成了。剩下的自动完成，比较快。但是和手工版本步骤的结果都是一样的。kubelet之后的安装是有问题的。我的环境是centos7.9 

menu
#set_local      手工完成
#init_all         手工完成
Containerd
init_local
init_etcd
init_ha_keep
init_k8s_master
init_k8s_all
最终的结果，和对应的‘手工版本的文档’的现象是一样的。
请cby-chen百忙中，再审阅一下！

 kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS    MESSAGE                         ERROR
controller-manager   Healthy   ok
etcd-0               Healthy   {"health":"true","reason":""}
etcd-1               Healthy   {"health":"true","reason":""}
etcd-2               Healthy   {"health":"true","reason":""}
scheduler            Healthy   ok
[root@k8s-master01 ~]# kubectl get nodes
No resources found

**Comment by cby-chen** [comment]
查看不到nodes 一般情况是kubelet没有正常启动，可以检查一下kubelet是否正常启动。同时可以看看containerd配置是否正常，比如配置中“ sandbox_image” “ SystemdCgroup” 这俩项配置。还有就是环境变量，以及host

**Comment by boboyada** [comment]
你的安装中，既有docker-ce的安装，也有containerd的安装。到底配置了启用谁？是否是这个冲突？因为在安装containerd时，提示已经被containerd.io替换

**Comment by boboyada** [comment]
[root@k8s-node01 ~]# systemctl status kubelet     检查，是运行的状态！但是日志提示找不到k8s-node01
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since 五 2022-05-13 13:38:40 CST; 3min 18s ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 1763 (kubelet)
    Tasks: 12
   Memory: 51.9M
   CGroup: /system.slice/kubelet.service
           └─1763 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --config=/etc/k...

5月 13 13:41:57 k8s-node01 kubelet[1763]: E0513 13:41:57.874585    1763 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 13:41:57 k8s-node01 kubelet[1763]: E0513 13:41:57.976610    1763 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 13:41:58 k8s-node01 kubelet[1763]: E0513 13:41:58.077782    1763 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 13:41:58 k8s-node01 kubelet[1763]: E0513 13:41:58.179071    1763 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 13:41:58 k8s-node01 kubelet[1763]: E0513 13:41:58.281117    1763 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 13:41:58 k8s-node01 kubelet[1763]: E0513 13:41:58.383272    1763 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 13:41:58 k8s-node01 kubelet[1763]: E0513 13:41:58.485468    1763 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 13:41:58 k8s-node01 kubelet[1763]: E0513 13:41:58.586768    1763 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 13:41:58 k8s-node01 kubelet[1763]: E0513 13:41:58.688739    1763 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 13:41:58 k8s-node01 kubelet[1763]: E0513 13:41:58.790073    1763 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
[root@k8s-node01 ~]#

**Comment by cby-chen** [comment]
看下这俩个配置

[root@k8s-master01 ~]# cat /etc/containerd/config.toml | grep sandbox_image    

            sandbox_image = "registry.cn-hangzhou.aliyuncs.com/chenby/pause:3.5"


[root@k8s-master01 ~]# cat /etc/containerd/config.toml | grep SystemdCgroup
            SystemdCgroup = true

**Comment by boboyada** [comment]
cat /etc/containerd/config.toml |grep sandbox_image
    sandbox_image = "registry.cn-hangzhou.aliyuncs.com/chenby/pause:3.6"
[root@k8s-node02 pki]# cat /etc/containerd/config.toml |grep SystemdCgoup
[root@k8s-node02 pki]# cat /etc/containerd/config.toml |grep SystemdCgroup
            SystemdCgroup = true

**Comment by boboyada** [comment]
日志：
[root@k8s-node02 pki]# systemctl status kubelet -l
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since 五 2022-05-13 15:32:07 CST; 1min 22s ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 4813 (kubelet)
    Tasks: 12
   Memory: 27.1M
   CGroup: /system.slice/kubelet.service
           └─4813 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --config=/etc/kubernetes/kubelet-conf.yml --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock --cgroup-driver=systemd --node-labels=node.kubernetes.io/node=''

5月 13 15:33:29 k8s-node02 kubelet[4813]: E0513 15:33:29.394027    4813 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:33:29 k8s-node02 kubelet[4813]: E0513 15:33:29.495697    4813 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:33:29 k8s-node02 kubelet[4813]: E0513 15:33:29.597465    4813 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:33:29 k8s-node02 kubelet[4813]: E0513 15:33:29.698415    4813 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:33:29 k8s-node02 kubelet[4813]: E0513 15:33:29.799947    4813 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:33:29 k8s-node02 kubelet[4813]: E0513 15:33:29.900442    4813 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:33:30 k8s-node02 kubelet[4813]: E0513 15:33:30.002241    4813 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:33:30 k8s-node02 kubelet[4813]: E0513 15:33:30.103297    4813 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:33:30 k8s-node02 kubelet[4813]: E0513 15:33:30.204193    4813 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:33:30 k8s-node02 kubelet[4813]: E0513 15:33:30.220511    4813 controller.go:144] failed to ensure lease exists, will retry in 7s, error: leases.coordination.k8s.io "k8s-node02" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
[root@k8s-node02 pki]#

**Comment by boboyada** [comment]
下面是# ### journal  -xe  的日志信息
[root@k8s-node02 pki]# systemctl restart kubelet
[root@k8s-node02 pki]# journalctl -xe -l
5月 13 15:40:17 k8s-node02 kubelet[5179]: E0513 15:40:17.942253    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:17 k8s-node02 kubelet[5179]: E0513 15:40:17.945522    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:17 k8s-node02 kubelet[5179]: I0513 15:40:17.946390    5179 kubelet_node_status.go:70] "Attempting to register node" node="k8s-node02"
5月 13 15:40:17 k8s-node02 kubelet[5179]: E0513 15:40:17.947493    5179 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create r
5月 13 15:40:17 k8s-node02 kubelet[5179]: E0513 15:40:17.947774    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:17 k8s-node02 kubelet[5179]: E0513 15:40:17.949822    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:17 k8s-node02 kubelet[5179]: E0513 15:40:17.951477    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.046258    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.083517    5179 controller.go:144] failed to ensure lease exists, will retry in 400ms, error: leases.coordination.k8s.io "k8s-node02" is forbidden: Use
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.147081    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:18 k8s-node02 kubelet[5179]: I0513 15:40:18.149480    5179 kubelet_node_status.go:70] "Attempting to register node" node="k8s-node02"
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.150973    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.151340    5179 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create r
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.153385    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.239946    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.247710    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.349426    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.451068    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.485585    5179 controller.go:144] failed to ensure lease exists, will retry in 800ms, error: leases.coordination.k8s.io "k8s-node02" is forbidden: Use
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.552156    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:18 k8s-node02 kubelet[5179]: I0513 15:40:18.552405    5179 kubelet_node_status.go:70] "Attempting to register node" node="k8s-node02"
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.553966    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.554104    5179 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create r
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.640964    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.652655    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.753392    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.840677    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.854082    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:18 k8s-node02 kubelet[5179]: W0513 15:40:18.889105    5179 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous"
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.889127    5179 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbi
5月 13 15:40:18 k8s-node02 kubelet[5179]: W0513 15:40:18.945046    5179 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.945068    5179 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.st
5月 13 15:40:18 k8s-node02 kubelet[5179]: E0513 15:40:18.954827    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.055446    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.156228    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: W0513 15:40:19.241194    5179 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "k8s-node02" is forbidden: User "system:ano
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.241216    5179 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "k8s-node02" is f
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.258077    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.287045    5179 controller.go:144] failed to ensure lease exists, will retry in 1.6s, error: leases.coordination.k8s.io "k8s-node02" is forbidden: User
5月 13 15:40:19 k8s-node02 kubelet[5179]: I0513 15:40:19.355306    5179 kubelet_node_status.go:70] "Attempting to register node" node="k8s-node02"
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.356861    5179 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create r
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.357288    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.358118    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.358146    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.439872    5179 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"k8s-node02.
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.458469    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: W0513 15:40:19.461636    5179 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden:
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.461658    5179 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtime
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.560156    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.660946    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.761685    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.862409    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.963126    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:19 k8s-node02 kubelet[5179]: E0513 15:40:19.967769    5179 certificate_manager.go:471] kubernetes.io/kube-apiserver-client-kubelet: Failed while requesting a signed certificate from the control
5月 13 15:40:20 k8s-node02 kubelet[5179]: E0513 15:40:20.063861    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:20 k8s-node02 kubelet[5179]: E0513 15:40:20.164506    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:20 k8s-node02 kubelet[5179]: E0513 15:40:20.265311    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:20 k8s-node02 kubelet[5179]: E0513 15:40:20.366068    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
5月 13 15:40:20 k8s-node02 kubelet[5179]: E0513 15:40:20.466810    5179 kubelet.go:2461] "Error getting node" err="node \"k8s-node02\" not found"
[root@k8s-node02 pki]#

**Comment by boboyada** [comment]
重新安装一遍，错误如下：
[root@k8s-node01 ~]# journalctl  -f -t kubelet
-- Logs begin at 五 2022-05-13 16:35:54 CST. --
5月 13 19:59:36 k8s-node01 kubelet[8240]: E0513 19:59:36.730122    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:36 k8s-node01 kubelet[8240]: E0513 19:59:36.830576    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:36 k8s-node01 kubelet[8240]: E0513 19:59:36.932723    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.034064    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.135224    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.236571    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.337990    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.439313    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.446549    8240 csi_plugin.go:297] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "k8s-node01" not found
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.540628    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.641142    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.742301    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.843759    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:37 k8s-node01 kubelet[8240]: E0513 19:59:37.945044    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.047295    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.149357    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:38 k8s-node01 kubelet[8240]: I0513 19:59:38.247068    8240 kubelet_node_status.go:70] "Attempting to register node" node="k8s-node01"
5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.249900    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.252446    8240 kubelet_node_status.go:92] "Unable to register node with API server" err="Node \"k8s-node01\" is invalid: metadata.labels: Invalid value: \"''\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" node="k8s-node01"
5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.350363    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.452477    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.554662    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.656783    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.758992    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
q5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.859696    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:38 k8s-node01 kubelet[8240]: E0513 19:59:38.960956    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:39 k8s-node01 kubelet[8240]: E0513 19:59:39.062190    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:39 k8s-node01 kubelet[8240]: E0513 19:59:39.162741    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:39 k8s-node01 kubelet[8240]: E0513 19:59:39.263287    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:39 k8s-node01 kubelet[8240]: E0513 19:59:39.365298    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:39 k8s-node01 kubelet[8240]: E0513 19:59:39.467520    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:39 k8s-node01 kubelet[8240]: E0513 19:59:39.568875    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
5月 13 19:59:39 k8s-node01 kubelet[8240]: E0513 19:59:39.670881    8240 kubelet.go:2461] "Error getting node" err="node \"k8s-node01\" not found"
^C

**Comment by boboyada** [comment]
> 查看不到nodes 一般情况是kubelet没有正常启动，可以检查一下kubelet是否正常启动。同时可以看看containerd配置是否正常，比如配置中“ sandbox_image” “ SystemdCgroup” 这俩项配置。还有就是环境变量，以及host

**我又重新仔细安装了一遍。还是在这个位置出现了错误，但是错误日志不一样了。好像哪个地方的参数值是'';:**
5月 13 20:42:48 k8s-master01 kubelet[16206]: I0513 20:42:48.893618   16206 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
5月 13 20:42:48 k8s-master01 kubelet[16206]: E0513 20:42:48.895004   16206 eviction_manager.go:254] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"k8s-master
01\" not found"
5月 13 20:42:48 k8s-master01 kubelet[16206]: E0513 20:42:48.920146   16206 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 13 20:42:48 k8s-master01 kubelet[16206]: I0513 20:42:48.920844   16206 kubelet_node_status.go:70] "Attempting to register node" node="k8s-master01"
5月 13 20:42:48 k8s-master01 kubelet[16206]: E0513 20:42:48.922807   16206 kubelet_node_status.go:92] "Unable to register node with API server" err="Node \"k8s-master01\" is invalid: metadata.lab
els: Invalid value: \"''\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  o
r 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" node="k8s-master01"
5月 13 20:42:49 k8s-master01 kubelet[16206]: E0513 20:42:49.021993   16206 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 13 20:42:49 k8s-master01 kubelet[16206]: E0513 20:42:49.122613   16206 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 13 20:42:49 k8s-master01 kubelet[16206]: I0513 20:42:49.124315   16206 kubelet_node_status.go:70] "Attempting to register node" node="k8s-master01"
5月 13 20:42:49 k8s-master01 kubelet[16206]: E0513 20:42:49.223370   16206 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 13 20:42:49 k8s-master01 kubelet[16206]: E0513 20:42:49.324319   16206 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"
5月 13 20:42:49 k8s-master01 kubelet[16206]: E0513 20:42:49.410987   16206 kubelet_node_status.go:92] "Unable to register node with API server" err="Node \"k8s-master01\" is invalid: metadata.lab
els: Invalid value: \"''\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  o
r 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" node="k8s-master01"
5月 13 20:42:49 k8s-master01 kubelet[16206]: E0513 20:42:49.425843   16206 kubelet.go:2461] "Error getting node" err="node \"k8s-master01\" not found"

**Comment by boboyada** [comment]
已经解决
