### ISSUE TITLE
请问ETCD是否支持ipv4/ipv6双栈配置？apiserver中该怎么配置etcd的双栈连接？

### ISSUE THREAD

**Issue by hellocn9** [cby-chen/Kubernetes#9]
您好，看了您的资料，感觉受益很多，想请问下如果支持双栈网络的话，ETCD是否也支持ipv4/ipv6双栈配置？如果支持，apiserver中该怎么配置etcd的双栈连接？谢谢

**Comment by cby-chen** [comment]
这个我没试过，应该是可以支持的吧。我的 IPV4/IPV6双栈 是用于kubernetes集群svc提供服务的v6可以在公网访问。集群内通讯可以使用IPV4 ，要是用IPV6通讯就把v4地址改成v6即可。我觉得集群内通讯，要么使用v4要么使用v6。
